version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: 220199
      MARIADB_ROOT_USER: root
      MARIADB_DATABASE: globalfungitest
    ports:
      - "33060:33060"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=220199"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
        - db_data:/var/lib/mysql
        - ./db/legacy_database_dump.sql:/docker-entrypoint-initdb.d/legacy_database_dump.sql
        - ./initial_migrations:/usr/src/app/scripts
    tmpfs:
        - /tmp
volumes:
  db_data: