version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: mypassword  # Corrected environment variable
    ports:
      - "33060:33060"  # Corrected port mapping
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=mypassword"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - type: tmpfs
        target: /tmp
      # Uncommented schema volume
      #- ./db/entrypoint.sql:/docker-entrypoint-initdb.d/00-schema.sql

  pgadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db  # Specify the database host
      PMA_USER: root  # Specify the database user
      PMA_PASSWORD: mypassword  # Specify the database password
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: tmpfs
        target: /tmp
