"""empty message

Revision ID: 397c03f16514
Revises: bc011574c833
Create Date: 2023-11-12 19:34:17.600344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '397c03f16514'
down_revision: Union[str, None] = 'bc011574c833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variants_migrated', 'sample_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'variants_migrated', 'Samples_migrated', ['sample_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variants_migrated', type_='foreignkey')
    op.alter_column('variants_migrated', 'sample_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
