name: Deploy FastAPI Application

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag your-registry/your-image-name:latest

    - name: Push Docker image
      run: |
        docker login your-registry --username ${{ secrets.REGISTRY_USER }} --password ${{ secrets.REGISTRY_PASSWORD }}
        docker push your-registry/your-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: Deploy to On-Premises Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull your-registry/your-image-name:latest
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker run -d --name fastapi-app -p 80:80 your-registry/your-image-name:latest
