name: Deploy FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag viktoriiasafiullina905/globalfungi_backend:latest
      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push viktoriiasafiullina905/globalfungi_backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to On-Premises Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ON_PREM_SERVER_HOST }}
          username: ${{ secrets.ON_PREM_SERVER_USER }}
          port: ${{ secrets.ON_PREM_SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull viktoriiasafiullina905/globalfungi_backend:latest
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d --name fastapi-app -p 80:80 viktoriiasafiullina905/globalfungi_backend:latest
